name             'nodejs-wrapper'
maintainer       'Dimitar PAvlov'
maintainer_email 'dimitar@shadez.info'
license          'All rights reserved'
description      'Installs/Configures nodejs'
long_description 'Installs/Configures nodejs'
version          '0.1.0'

depends 'imagemagick'
depends 'nodejs'
